title: Asciidoctor
description: A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook, PDF, and other formats.
author: Asciidoctor Project
blog_path: /news
# FIXME timezone will need to be specified per post for a global team
local_tz: America/Denver
disqus: asciidoctor
disqus_generate_id: true
disqus_developer: true
asciidoctor:
  :safe: :unsafe
  :base_dir: ~
  :attributes:
    allow-uri-read: ''
    #cache-uri: ''
    attribute-missing: 'warn'
    relfileprefix: '../@'
    relfilesuffix: '/@'
    idprefix: ''
    idseparator: '-'
    icons: 'font@'
    sectanchors: ''
    #source-highlighter: 'highlight.js'
    source-highlighter: 'coderay'
    prewrap!: '@'
haml:
  :ugly: true
slim|html:
  :format: :html
# NOTE if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: ~
    #show_drafts: false
  deploy-preview:
    deploy: ~
  production:
    base_url: https://asciidoctor.org
    disqus_developer: false
    # long-hand form is for Asciidoctor
    google_analytics_account: &ga UA-38215684-1
    google_analytics:
      account: *ga
    scss:
      :line_numbers: false
      :style: :compressed
    #compass_output_style: compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy: ~
    #deploy:
    #  host: github_pages
    #  branch: gh-pages
