title: Asciidoctor
description: An open source implementation of AsciiDoc in Ruby
author: Asciidoctor Project
blog_path: /news
# FIXME timezone will need to be specified per post for a global team
local_tz: America/Denver
disqus: asciidoctor
disqus_generate_id: true
disqus_developer: true
haml:
  :ugly: true
asciidoctor:
# enable compact after upgrade to Asciidoctor 0.1.2
#  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: highlight.js
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://asciidoctor.org
    disqus_developer: false
    google_analytics: UA-38215684-1
    compass_output_style: :compressed
    # TODO enable minify once we verify it's working as expected
    #minify: true
    deploy:
      host: github_pages
      branch: master
