name: CI
on: pull_request
jobs:
  activate:
    if: "!endsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Proceed
      run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    env:
      BUNDLE_BUILD__NOKOGIRI: --use-system-libraries
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites for Nokogiri
      run: sudo apt-get install libxslt1-dev
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Run validator
      run: bundle exec rake pr
